version: '3.8'

services:
  #=====================NGINX=============================
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    #depends_on:
      #- wordpress
    networks:
      - infra_network
    restart: always
    environment:
      - NGINX_TLS_PROTOCOLS=${TLS_VERSIONS}
      - DOMAIN_NAME=${DOMAIN_NAME}
  #=====================MARIADB=============================
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - infra_network
    restart: always
    environment:
      SQL_ROOT_PWD: ${SQL_ROOT_PWD}
      SQL_DB_NAME: ${SQL_DB_NAME}
      SQL_ADMIN: ${SQL_ADMIN}
      SQL_PASSWORD: ${SQL_PASSWORD}
  #======================WORDPRESS============================

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_VOLUME}
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_VOLUME}
    
networks:
  infra_network:
    driver: bridge
  