version: '3.8'

services:
  #=====================MARIADB===================================
  mariadb:
    container_name: mariadb
    environment:
      - SQL_ROOT_PWD=${SQL_ROOT_PWD}
      - SQL_DB_NAME=${SQL_DB_NAME}
      - SQL_ADMIN=${SQL_ADMIN}
      - SQL_PASSWORD=${SQL_PASSWORD}
    build: 
      context: requirements/mariadb/
    env_file:
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - infra_network
    restart: always
  #======================WORDPRESS================================
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SQL_ROOT_PWD=${SQL_ROOT_PWD}
      - SQL_DB_NAME=${SQL_DB_NAME}
      - SQL_ADMIN=${SQL_ADMIN}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - WP_DB_HOST=${WP_DB_HOST}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_ROOT_PASSWORD=${WP_ROOT_PASSWORD}
      - WP_TABLE_PREFIX=${WP_TABLE_PREFIX}
      - WPB_TITLE=${WPB_TITLE}
      - WPB_AUSER_USERNAME=${WPB_AUSER_USERNAME}
      - WPB_AUSER_PASSWORD=${WPB_AUSER_PASSWORD}
      - WPB_AUSER_EMAIL=${WPB_AUSER_EMAIL}
      - WPB_RUSER_USERNAME=${WPB_RUSER_USERNAME}
      - WPB_RUSER_PASSWORD=${WPB_RUSER_PASSWORD}
      - WPB_RUSER_EMAIL=${WPB_RUSER_EMAIL}
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - infra_network
    restart: always
  #=====================NGINX=====================================
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - infra_network
    restart: always
    env_file:
      - .env
    environment:
      - NGINX_TLS_PROTOCOLS=${TLS_VERSIONS}
      - DOMAIN_NAME=${DOMAIN_NAME}
###################################################################
volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_VOLUME}
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_VOLUME}
###################################################################
networks:
  infra_network:
    driver: bridge
  