version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html
    #depends_on:
      #- wordpress
    networks:
      - infra_network
    restart: always
    environment:
      - NGINX_TLS_PROTOCOLS=${TLS_VERSIONS}
      - DOMAIN_NAME=${DOMAIN_NAME}

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - infra_network
    restart: always
    environment:
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR: ${WP_DATABASE_USR}
      WP_DATABASE_PWD: ${WP_DATABASE_PWD}
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
    
  
volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      device: ${WORDPRESS_VOLUME}
  mariadb-volume:
    driver: local
    driver_opts:
      device: ${MARIADB_VOLUME}

networks:
  infra_network:
    driver: bridge