version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - wordpress-volume:/Users/reda/school_projects/inception/project/srcs/volumes/wordpress-volume
    environment:
      - NGINX_TLS_PROTOCOLS=TLSv1.2 TLSv1.3
      - DOMAIN_NAME="rnabil.1337.ma"
    networks:
      - infra_network_exposed

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    ports:
      - "3306:3306"
    volumes:
      - "~/Desktop/inception/mariadb:/var/lib/mysql"
    networks:
      - infra_network_obscure
    restart: always
    environment:
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
    
  
volumes:
  wordpress-volume:
  mariadb-volume:

networks:
  infra_network_exposed:
    driver: bridge
  infra_network_obscure:
    driver: bridge